- name: "Check if directory {{ home_dir }}/nerd-fonts exists"
  ansible.builtin.stat:
    path: "{{ home_dir }}/nerd-fonts"
  register: nerd_fonts_dir

- name: "Clone Nerd Fonts repo to {{ home_dir }}/nerd-fonts"
  ansible.builtin.git:
    repo: https://github.com/ryanoasis/nerd-fonts.git
    depth: 1
    dest: "{{ home_dir }}/nerd-fonts"
    update: no
  when: not nerd_fonts_dir.stat.exists

- name: Instructions for installing fonts
  ansible.builtin.debug:
    msg: "Install the fonts you want manually. E.g. run `source {{ home_dir }}/nerd-fonts/install.sh JetBrainsMono`"
